#!/usr/bin/env bash
# Creates a PID file and handles signals properly

echo "$$" | sudo tee /var/run/myscript.pid >/dev/null

cleanup() {
    sudo rm -f /var/run/myscript.pid
    exit 0
}

sigterm_handler() {
    echo "I hate the kill command"
    cleanup
}

sigint_handler() {
    echo "Y U no love me?!"
}

trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap cleanup SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
